// flow-typed signature: 03a5ddf0f0ae3d85202809e6cbf84c64
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v^2.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'case-sensitive-paths-webpack-plugin/index' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
declare module 'case-sensitive-paths-webpack-plugin/index.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
