// flow-typed signature: b765a8ad5be9ccd5797d170f747d77a6
// flow-typed version: <<STUB>>/get-port_v^3.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'get-port/index' {
  declare module.exports: $Exports<'get-port'>;
}
declare module 'get-port/index.js' {
  declare module.exports: $Exports<'get-port'>;
}
