// flow-typed signature: 943ace6ec2907a267a273ab91cb8039b
// flow-typed version: <<STUB>>/node-mkdirp_v^0.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-mkdirp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-mkdirp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-mkdirp/index' {
  declare module.exports: $Exports<'node-mkdirp'>;
}
declare module 'node-mkdirp/index.js' {
  declare module.exports: $Exports<'node-mkdirp'>;
}
