// flow-typed signature: cd43136f914def9c10cec98cd6c5a1ec
// flow-typed version: <<STUB>>/nyan-progress-webpack-plugin_vgithub:SaraVieira/nyan-progress-webpack-plugin/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyan-progress-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyan-progress-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nyan-progress-webpack-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nyan-progress-webpack-plugin/index' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin'>;
}
declare module 'nyan-progress-webpack-plugin/index.js' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin'>;
}
declare module 'nyan-progress-webpack-plugin/test/index.js' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin/test/index'>;
}
