// flow-typed signature: 983f5e796496c4ffb7aeef82b94ff9ee
// flow-typed version: <<STUB>>/nyan-progress-webpack-plugin_v^1.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyan-progress-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyan-progress-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nyan-progress-webpack-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nyan-progress-webpack-plugin/index' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin'>;
}
declare module 'nyan-progress-webpack-plugin/index.js' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin'>;
}
declare module 'nyan-progress-webpack-plugin/test/index.js' {
  declare module.exports: $Exports<'nyan-progress-webpack-plugin/test/index'>;
}
