// flow-typed signature: 5bb6ddb6c33bbe160e5d916cddf2a46f
// flow-typed version: <<STUB>>/postcss-caralho_v^1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-caralho'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-caralho' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-caralho/index' {
  declare module.exports: $Exports<'postcss-caralho'>;
}
declare module 'postcss-caralho/index.js' {
  declare module.exports: $Exports<'postcss-caralho'>;
}
