// flow-typed signature: e5ef2d2fe93836009b0be733e1770904
// flow-typed version: <<STUB>>/postcss-less-vars_v^1.2.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-less-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-less-vars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-less-vars/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-less-vars/index' {
  declare module.exports: $Exports<'postcss-less-vars'>;
}
declare module 'postcss-less-vars/index.js' {
  declare module.exports: $Exports<'postcss-less-vars'>;
}
declare module 'postcss-less-vars/test.js' {
  declare module.exports: $Exports<'postcss-less-vars/test'>;
}
