// flow-typed signature: 089029db33f815db668e612ed1fb200f
// flow-typed version: <<STUB>>/statful-client_v^4.1.5/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'statful-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'statful-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'statful-client/lib/client' {
  declare module.exports: any;
}

declare module 'statful-client/lib/config-helper' {
  declare module.exports: any;
}

declare module 'statful-client/spec/common.spec' {
  declare module.exports: any;
}

declare module 'statful-client/spec/counter.spec' {
  declare module.exports: any;
}

declare module 'statful-client/spec/gauge.spec' {
  declare module.exports: any;
}

declare module 'statful-client/spec/timer.spec' {
  declare module.exports: any;
}

declare module 'statful-client/spec/tools/https-server' {
  declare module.exports: any;
}

declare module 'statful-client/spec/tools/udp-server' {
  declare module.exports: any;
}

declare module 'statful-client/statful' {
  declare module.exports: any;
}

// Filename aliases
declare module 'statful-client/lib/client.js' {
  declare module.exports: $Exports<'statful-client/lib/client'>;
}
declare module 'statful-client/lib/config-helper.js' {
  declare module.exports: $Exports<'statful-client/lib/config-helper'>;
}
declare module 'statful-client/spec/common.spec.js' {
  declare module.exports: $Exports<'statful-client/spec/common.spec'>;
}
declare module 'statful-client/spec/counter.spec.js' {
  declare module.exports: $Exports<'statful-client/spec/counter.spec'>;
}
declare module 'statful-client/spec/gauge.spec.js' {
  declare module.exports: $Exports<'statful-client/spec/gauge.spec'>;
}
declare module 'statful-client/spec/timer.spec.js' {
  declare module.exports: $Exports<'statful-client/spec/timer.spec'>;
}
declare module 'statful-client/spec/tools/https-server.js' {
  declare module.exports: $Exports<'statful-client/spec/tools/https-server'>;
}
declare module 'statful-client/spec/tools/udp-server.js' {
  declare module.exports: $Exports<'statful-client/spec/tools/udp-server'>;
}
declare module 'statful-client/statful.js' {
  declare module.exports: $Exports<'statful-client/statful'>;
}
