// flow-typed signature: 6033e7a2c060da20bddd4aeeb97420d1
// flow-typed version: <<STUB>>/tvg-ui-bootstrap_v^1.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tvg-ui-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tvg-ui-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tvg-ui-bootstrap/config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tvg-ui-bootstrap/config/webpack.config.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/config/webpack.config'>;
}
