// flow-typed signature: d9380c007455db9005360c9174cc6684
// flow-typed version: <<STUB>>/tvg-conf_v^0.1.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tvg-conf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tvg-conf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tvg-conf/content/base' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/production/ia' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/production/nj' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/production/pa' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/production/tvg' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/qa/ia' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/qa/nj' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/qa/pa' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/qa/tvg' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/staging/ia' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/staging/nj' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/staging/pa' {
  declare module.exports: any;
}

declare module 'tvg-conf/content/staging/tvg' {
  declare module.exports: any;
}

declare module 'tvg-conf/dist/tvg-conf.umd' {
  declare module.exports: any;
}

declare module 'tvg-conf/lib/brand' {
  declare module.exports: any;
}

declare module 'tvg-conf/lib/content' {
  declare module.exports: any;
}

declare module 'tvg-conf/lib/device' {
  declare module.exports: any;
}

declare module 'tvg-conf/lib/environment' {
  declare module.exports: any;
}

declare module 'tvg-conf/lib/mediator-actions' {
  declare module.exports: any;
}

declare module 'tvg-conf/test/index.test' {
  declare module.exports: any;
}

declare module 'tvg-conf/webpack.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tvg-conf/content/base.js' {
  declare module.exports: $Exports<'tvg-conf/content/base'>;
}
declare module 'tvg-conf/content/production/ia.js' {
  declare module.exports: $Exports<'tvg-conf/content/production/ia'>;
}
declare module 'tvg-conf/content/production/nj.js' {
  declare module.exports: $Exports<'tvg-conf/content/production/nj'>;
}
declare module 'tvg-conf/content/production/pa.js' {
  declare module.exports: $Exports<'tvg-conf/content/production/pa'>;
}
declare module 'tvg-conf/content/production/tvg.js' {
  declare module.exports: $Exports<'tvg-conf/content/production/tvg'>;
}
declare module 'tvg-conf/content/qa/ia.js' {
  declare module.exports: $Exports<'tvg-conf/content/qa/ia'>;
}
declare module 'tvg-conf/content/qa/nj.js' {
  declare module.exports: $Exports<'tvg-conf/content/qa/nj'>;
}
declare module 'tvg-conf/content/qa/pa.js' {
  declare module.exports: $Exports<'tvg-conf/content/qa/pa'>;
}
declare module 'tvg-conf/content/qa/tvg.js' {
  declare module.exports: $Exports<'tvg-conf/content/qa/tvg'>;
}
declare module 'tvg-conf/content/staging/ia.js' {
  declare module.exports: $Exports<'tvg-conf/content/staging/ia'>;
}
declare module 'tvg-conf/content/staging/nj.js' {
  declare module.exports: $Exports<'tvg-conf/content/staging/nj'>;
}
declare module 'tvg-conf/content/staging/pa.js' {
  declare module.exports: $Exports<'tvg-conf/content/staging/pa'>;
}
declare module 'tvg-conf/content/staging/tvg.js' {
  declare module.exports: $Exports<'tvg-conf/content/staging/tvg'>;
}
declare module 'tvg-conf/dist/tvg-conf.umd.js' {
  declare module.exports: $Exports<'tvg-conf/dist/tvg-conf.umd'>;
}
declare module 'tvg-conf/index' {
  declare module.exports: $Exports<'tvg-conf'>;
}
declare module 'tvg-conf/index.js' {
  declare module.exports: $Exports<'tvg-conf'>;
}
declare module 'tvg-conf/lib/brand.js' {
  declare module.exports: $Exports<'tvg-conf/lib/brand'>;
}
declare module 'tvg-conf/lib/content.js' {
  declare module.exports: $Exports<'tvg-conf/lib/content'>;
}
declare module 'tvg-conf/lib/device.js' {
  declare module.exports: $Exports<'tvg-conf/lib/device'>;
}
declare module 'tvg-conf/lib/environment.js' {
  declare module.exports: $Exports<'tvg-conf/lib/environment'>;
}
declare module 'tvg-conf/lib/mediator-actions.js' {
  declare module.exports: $Exports<'tvg-conf/lib/mediator-actions'>;
}
declare module 'tvg-conf/test/index.test.js' {
  declare module.exports: $Exports<'tvg-conf/test/index.test'>;
}
declare module 'tvg-conf/webpack.conf.js' {
  declare module.exports: $Exports<'tvg-conf/webpack.conf'>;
}
