// flow-typed signature: 5dd82b2260802ef453c6f41b2ce2e026
// flow-typed version: <<STUB>>/tvg-ui-bootstrap_v^4.1.12/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tvg-ui-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tvg-ui-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tvg-ui-bootstrap/Colors/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/ButtonGroup/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/ButtonGroup/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Buttons/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Buttons/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Deposit/DepositAmount/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Deposit/DepositAmount/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/containerItem/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/containerItem/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Item/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Item/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Label/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Label/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/List/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/List/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Title/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Dropdown/Title/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Checkbox/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Checkbox/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Input/Error/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Input/Error/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Input/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Input/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Select/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Form/Select/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Loading/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Loading/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Modal/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Modal/__tests__/Modal.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Modal/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Modal/Modal' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/ModuleContent/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/ModuleContent/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/ModuleHeader/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Module/ModuleHeader/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Mtp/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Notifications/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Notifications/notification' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/props.example' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Video/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/RaceResults/Video/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Switch/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Switch/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Tooltip/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/TVGVideoWrapper/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/TVGVideoWrapper/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/actions' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/actions.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/Login/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/Login/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/config/jest/fileTransformer' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.16.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-dynamic-import-node_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-syntax-dynamic-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-inline-elements_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-latest_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-node6_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react-optimize_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/loadash_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/numeral_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-clone-with-props_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-click-outside_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-mediator_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/url-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/Icons/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/postcss.config' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/styleguide.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tvg-ui-bootstrap/Colors/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/Colors/index'>;
}
declare module 'tvg-ui-bootstrap/components/ButtonGroup/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/ButtonGroup/index'>;
}
declare module 'tvg-ui-bootstrap/components/ButtonGroup/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/ButtonGroup/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Buttons/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Buttons/index'>;
}
declare module 'tvg-ui-bootstrap/components/Buttons/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Buttons/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Deposit/DepositAmount/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Deposit/DepositAmount/index'>;
}
declare module 'tvg-ui-bootstrap/components/Deposit/DepositAmount/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Deposit/DepositAmount/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/containerItem/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/containerItem/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/containerItem/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/containerItem/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Item/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Item/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Item/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Item/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Label/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Label/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Label/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Label/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/List/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/List/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/List/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/List/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Title/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Title/index'>;
}
declare module 'tvg-ui-bootstrap/components/Dropdown/Title/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Dropdown/Title/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Checkbox/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Checkbox/index'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Checkbox/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Checkbox/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Input/Error/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Input/Error/index'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Input/Error/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Input/Error/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Input/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Input/index'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Input/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Input/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Select/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Select/index'>;
}
declare module 'tvg-ui-bootstrap/components/Form/Select/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Form/Select/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/index'>;
}
declare module 'tvg-ui-bootstrap/components/Loading/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Loading/index'>;
}
declare module 'tvg-ui-bootstrap/components/Loading/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Loading/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Modal/__tests__/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Modal/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Modal/__tests__/Modal.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Modal/__tests__/Modal.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Modal/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Modal/index'>;
}
declare module 'tvg-ui-bootstrap/components/Modal/Modal.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Modal/Modal'>;
}
declare module 'tvg-ui-bootstrap/components/Module/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/index'>;
}
declare module 'tvg-ui-bootstrap/components/Module/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Module/ModuleContent/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/ModuleContent/index'>;
}
declare module 'tvg-ui-bootstrap/components/Module/ModuleContent/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/ModuleContent/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Module/ModuleHeader/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/ModuleHeader/index'>;
}
declare module 'tvg-ui-bootstrap/components/Module/ModuleHeader/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Module/ModuleHeader/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Mtp/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Mtp/index'>;
}
declare module 'tvg-ui-bootstrap/components/Notifications/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Notifications/index'>;
}
declare module 'tvg-ui-bootstrap/components/Notifications/notification.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Notifications/notification'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/MultiRaceBet/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/PayoffsBlocker/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Payoffs/SimpleBet/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/props.example.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/props.example'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/ResultsToggle/index'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Video/__tests__/index.spec.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Video/__tests__/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/RaceResults/Video/index.jsx' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/RaceResults/Video/index'>;
}
declare module 'tvg-ui-bootstrap/components/Switch/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Switch/index'>;
}
declare module 'tvg-ui-bootstrap/components/Switch/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Switch/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Tooltip/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Tooltip/index'>;
}
declare module 'tvg-ui-bootstrap/components/TVGVideoWrapper/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/TVGVideoWrapper/index'>;
}
declare module 'tvg-ui-bootstrap/components/TVGVideoWrapper/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/TVGVideoWrapper/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/actions.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/actions'>;
}
declare module 'tvg-ui-bootstrap/components/Video/actions.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/actions.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/index'>;
}
declare module 'tvg-ui-bootstrap/components/Video/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/Login/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/Login/index'>;
}
declare module 'tvg-ui-bootstrap/components/Video/Login/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/Login/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/NoVideo/index'>;
}
declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/NoVideo/index.spec'>;
}
declare module 'tvg-ui-bootstrap/config/jest/fileTransformer.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/config/jest/fileTransformer'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.16.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/axios_v0.16.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-dynamic-import-node_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-dynamic-import-node_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-syntax-dynamic-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-syntax-dynamic-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-inline-elements_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-react-inline-elements_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-latest_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-latest_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-node6_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-node6_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react-optimize_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react-optimize_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/loadash_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/loadash_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/numeral_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/numeral_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-clone-with-props_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-addons-clone-with-props_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-click-outside_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-click-outside_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-mediator_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/tvg-mediator_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/url-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/url-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/Icons/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/Icons/index'>;
}
declare module 'tvg-ui-bootstrap/postcss.config.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/postcss.config'>;
}
declare module 'tvg-ui-bootstrap/styleguide.config.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/styleguide.config'>;
}
