// flow-typed signature: 63ae386351c62dc601007296ce9fb04a
// flow-typed version: <<STUB>>/tvg-ui-bootstrap_v^3.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tvg-ui-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tvg-ui-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tvg-ui-bootstrap/Colors/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Buttons/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Loading/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Mtp/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Notifications/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Notifications/notification' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/actions' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/actions.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.spec' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/config/jest/fileTransformer' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/Icons/index' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/postcss.config' {
  declare module.exports: any;
}

declare module 'tvg-ui-bootstrap/styleguide.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tvg-ui-bootstrap/Colors/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/Colors/index'>;
}
declare module 'tvg-ui-bootstrap/components/Buttons/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Buttons/index'>;
}
declare module 'tvg-ui-bootstrap/components/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/index'>;
}
declare module 'tvg-ui-bootstrap/components/Loading/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Loading/index'>;
}
declare module 'tvg-ui-bootstrap/components/Mtp/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Mtp/index'>;
}
declare module 'tvg-ui-bootstrap/components/Notifications/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Notifications/index'>;
}
declare module 'tvg-ui-bootstrap/components/Notifications/notification.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Notifications/notification'>;
}
declare module 'tvg-ui-bootstrap/components/Video/actions.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/actions'>;
}
declare module 'tvg-ui-bootstrap/components/Video/actions.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/actions.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/index'>;
}
declare module 'tvg-ui-bootstrap/components/Video/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/index.spec'>;
}
declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/NoVideo/index'>;
}
declare module 'tvg-ui-bootstrap/components/Video/NoVideo/index.spec.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/components/Video/NoVideo/index.spec'>;
}
declare module 'tvg-ui-bootstrap/config/jest/fileTransformer.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/config/jest/fileTransformer'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/autoprefixer_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/axios_v0.15.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/axios-mock-adapter_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-env_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/clean-css_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/extract-text-webpack-plugin_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/file-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/html-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/http-server_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/identity-obj-proxy_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/less_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/less-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/moment_v2.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/normalize.css_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/npm-run-all_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-cssnext_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/postcss-smart-import_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/publish-please_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/react-styleguidist_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-inline-react_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-react-loader_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/svg-sprite_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/tvg-conf_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'tvg-ui-bootstrap/Icons/index.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/Icons/index'>;
}
declare module 'tvg-ui-bootstrap/postcss.config.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/postcss.config'>;
}
declare module 'tvg-ui-bootstrap/styleguide.config.js' {
  declare module.exports: $Exports<'tvg-ui-bootstrap/styleguide.config'>;
}
