// flow-typed signature: 7391ae812490d3e31262db3153be2195
// flow-typed version: <<STUB>>/tvg-mediator_v^0.6.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tvg-mediator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tvg-mediator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tvg-mediator/dist/tvg-mediator.umd' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'tvg-mediator/src/__tests__/Mediator.spec' {
  declare module.exports: any;
}

declare module 'tvg-mediator/src/index' {
  declare module.exports: any;
}

declare module 'tvg-mediator/src/Mediator' {
  declare module.exports: any;
}

declare module 'tvg-mediator/src/utils' {
  declare module.exports: any;
}

declare module 'tvg-mediator/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tvg-mediator/dist/tvg-mediator.umd.js' {
  declare module.exports: $Exports<'tvg-mediator/dist/tvg-mediator.umd'>;
}
declare module 'tvg-mediator/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'tvg-mediator/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'tvg-mediator/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'tvg-mediator/src/__tests__/Mediator.spec.js' {
  declare module.exports: $Exports<'tvg-mediator/src/__tests__/Mediator.spec'>;
}
declare module 'tvg-mediator/src/index.js' {
  declare module.exports: $Exports<'tvg-mediator/src/index'>;
}
declare module 'tvg-mediator/src/Mediator.js' {
  declare module.exports: $Exports<'tvg-mediator/src/Mediator'>;
}
declare module 'tvg-mediator/src/utils.js' {
  declare module.exports: $Exports<'tvg-mediator/src/utils'>;
}
declare module 'tvg-mediator/webpack.config.js' {
  declare module.exports: $Exports<'tvg-mediator/webpack.config'>;
}
