// flow-typed signature: 8948a0b214e012e4def3ae171d59a69d
// flow-typed version: <<STUB>>/winston-gke_v^1.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-gke'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-gke' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-gke/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-gke/index' {
  declare module.exports: $Exports<'winston-gke'>;
}
declare module 'winston-gke/index.js' {
  declare module.exports: $Exports<'winston-gke'>;
}
declare module 'winston-gke/test.js' {
  declare module.exports: $Exports<'winston-gke/test'>;
}
